defmodule Mix.Tasks.SelectoPostgrex.Setup do
  @shortdoc "Run all SQL setup files from priv/sql/"
  @moduledoc """
  Execute all SQL files from `priv/sql/` against a Postgrex database connection.

  This task runs all `.sql` files generated by the `selecto_postgrex.gen.*` tasks.

  ## Examples

      # Using DATABASE_URL environment variable
      mix selecto_postgrex.setup

      # Using explicit database URL
      mix selecto_postgrex.setup --database-url postgres://user:pass@localhost/mydb

      # Using individual connection parameters
      mix selecto_postgrex.setup --host localhost --database mydb --username postgres

      # Run specific SQL file
      mix selecto_postgrex.setup --file priv/sql/create_saved_views.sql

      # Dry run - show what would be executed
      mix selecto_postgrex.setup --dry-run

  ## Options

    * `--database-url` / `-u` - Database URL (default: DATABASE_URL env var)
    * `--host` / `-h` - Database hostname
    * `--port` / `-P` - Database port
    * `--database` / `-D` - Database name
    * `--username` / `-U` - Database username
    * `--password` / `-W` - Database password
    * `--file` / `-f` - Run a specific SQL file instead of all files
    * `--sql-dir` - Directory containing SQL files (default: priv/sql)
    * `--dry-run` / `-d` - Show what would be executed without running
  """

  use Igniter.Mix.Task

  alias SelectoPostgrexMix.{Connection, ConnectionOpts, SqlRunner}

  @impl Igniter.Mix.Task
  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      group: :selecto,
      example: "mix selecto_postgrex.setup",
      schema:
        ConnectionOpts.connection_schema() ++
          [
            file: :string,
            sql_dir: :string,
            dry_run: :boolean
          ],
      aliases:
        ConnectionOpts.connection_aliases() ++
          [
            f: :file,
            d: :dry_run
          ]
    }
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    parsed_args = igniter.args.options
    conn_opts = ConnectionOpts.from_parsed_args(parsed_args)
    sql_dir = parsed_args[:sql_dir] || "priv/sql"

    if parsed_args[:dry_run] do
      show_dry_run(sql_dir, parsed_args[:file])
      igniter
    else
      case run_setup(conn_opts, sql_dir, parsed_args[:file]) do
        {:ok, msg} ->
          Igniter.add_notice(igniter, msg)

        {:error, msg} ->
          Igniter.add_warning(igniter, msg)
      end
    end
  end

  defp show_dry_run(sql_dir, specific_file) do
    if specific_file do
      IO.puts("\nDRY RUN: Would execute SQL file: #{specific_file}")
    else
      files =
        Path.join(sql_dir, "*.sql")
        |> Path.wildcard()
        |> Enum.sort()

      if Enum.empty?(files) do
        IO.puts("\nDRY RUN: No SQL files found in #{sql_dir}/")
      else
        IO.puts("\nDRY RUN: Would execute #{length(files)} SQL file(s) from #{sql_dir}/:")

        Enum.each(files, fn file ->
          IO.puts("  * #{file}")
        end)
      end
    end
  end

  defp run_setup(conn_opts, sql_dir, specific_file) do
    if specific_file do
      run_single_file(conn_opts, specific_file)
    else
      run_all_files(conn_opts, sql_dir)
    end
  end

  defp run_single_file(conn_opts, file_path) do
    unless File.exists?(file_path) do
      {:error, "SQL file not found: #{file_path}"}
    else
      Connection.with_connection(conn_opts, fn conn ->
        case SqlRunner.run_sql_file(conn, file_path) do
          {:ok, _label, count} ->
            {:ok, "Successfully executed #{count} statement(s) from #{file_path}"}

          {:error, _label, error} ->
            {:error, "Error executing #{file_path}: #{inspect(error)}"}
        end
      end)
    end
  end

  defp run_all_files(conn_opts, sql_dir) do
    unless File.dir?(sql_dir) do
      {:error,
       "SQL directory not found: #{sql_dir}. Run a gen task first (e.g., mix selecto_postgrex.gen.saved_views)"}
    else
      case SqlRunner.run_sql_directory(sql_dir, conn_opts: conn_opts) do
        {:ok, :no_files} ->
          {:error, "No SQL files found in #{sql_dir}/. Run a gen task first."}

        {:ok, count} ->
          {:ok, "Successfully executed #{count} SQL file(s) from #{sql_dir}/"}

        {:error, errors} ->
          error_msgs =
            Enum.map(errors, fn {:error, file, err} -> "  #{file}: #{inspect(err)}" end)

          {:error, "Errors executing SQL files:\n#{Enum.join(error_msgs, "\n")}"}
      end
    end
  end
end
