defmodule Mix.Tasks.SelectoPostgrex.Gen.FilterSets do
  @shortdoc "Generate filter sets implementation using Postgrex (no Ecto)"
  @moduledoc """
  Generate filter sets implementation for SelectoComponents using raw SQL
  and Postgrex contexts (no Ecto required).

  ## Usage

      mix selecto_postgrex.gen.filter_sets MyApp [options]

  ## Options

    * `--context-module` - Context module name (default: MyApp.FilterSets)
    * `--schema-module` - Compatibility option (not used in Postgrex mode)
    * `--table` - Table name (default: filter_sets)
    * `--repo` - Compatibility option (not used in Postgrex mode)
    * `--connection-name` - Named Postgrex connection (default: MyApp.Database)
    * `--no-migration` - Skip SQL file generation
    * `--no-tests` - Skip test file generation

  ## Generated Files

  - `priv/sql/create_filter_sets.sql` - SQL to create the table
  - `lib/APP/filter_sets.ex` - Context using Postgrex.query
  """

  use Mix.Task
  import Mix.Generator

  @requirements ["app.config"]

  def run(args) do
    {opts, positional, _} =
      OptionParser.parse(args,
        switches: [
          context_module: :string,
          schema_module: :string,
          table: :string,
          repo: :string,
          connection_name: :string,
          migration: :boolean,
          tests: :boolean
        ]
      )

    app_module = List.first(positional)

    if is_nil(app_module) do
      Mix.raise("Expected the base module name, got: #{inspect(args)}")
    end

    app_name = Macro.underscore(app_module)

    config = %{
      app_module: app_module,
      app_name: app_name,
      context_module: opts[:context_module] || "#{app_module}.FilterSets",
      schema_module: opts[:schema_module],
      table: opts[:table] || "filter_sets",
      repo: opts[:repo],
      connection_name: opts[:connection_name] || "#{app_module}.Database",
      migration: Keyword.get(opts, :migration, true),
      tests: Keyword.get(opts, :tests, true)
    }

    maybe_warn_compatibility_options(config)

    Mix.shell().info("Generating filter sets implementation for #{app_module}...")

    if config.migration do
      generate_sql(config)
    end

    generate_context(config)

    if config.tests do
      generate_tests(config)
    end

    print_instructions(config)
  end

  defp generate_sql(config) do
    sql_path = "priv/sql"
    create_directory(sql_path)

    sql_file = Path.join(sql_path, "create_#{config.table}.sql")

    content = """
    -- Filter sets table for SelectoComponents
    -- Generated by mix selecto_postgrex.gen.filter_sets
    -- Run with: mix selecto_postgrex.setup

    CREATE TABLE IF NOT EXISTS #{config.table} (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      name VARCHAR(100) NOT NULL,
      description TEXT,
      domain VARCHAR(255) NOT NULL,
      filters JSONB NOT NULL DEFAULT '{}',
      user_id VARCHAR(255) NOT NULL,
      is_default BOOLEAN NOT NULL DEFAULT false,
      is_shared BOOLEAN NOT NULL DEFAULT false,
      is_system BOOLEAN NOT NULL DEFAULT false,
      usage_count INTEGER NOT NULL DEFAULT 0,
      inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_#{config.table}_user_domain ON #{config.table} (user_id, domain);
    CREATE INDEX IF NOT EXISTS idx_#{config.table}_domain_shared ON #{config.table} (domain, is_shared);
    CREATE INDEX IF NOT EXISTS idx_#{config.table}_domain_system ON #{config.table} (domain, is_system);
    CREATE INDEX IF NOT EXISTS idx_#{config.table}_user_default ON #{config.table} (user_id, is_default);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table}_user_domain_name ON #{config.table} (user_id, domain, name);
    """

    create_file(sql_file, content)
  end

  defp generate_context(config) do
    context_path = "lib/#{config.app_name}/filter_sets.ex"
    create_directory(Path.dirname(context_path))

    content = """
    defmodule #{config.context_module} do
      @moduledoc \"\"\"
      Context for managing saved filter sets.
      Implements SelectoComponents.FilterSetsBehaviour using Postgrex (no Ecto).

      Generated by mix selecto_postgrex.gen.filter_sets
      \"\"\"

      @behaviour SelectoComponents.FilterSetsBehaviour

      @conn #{config.connection_name}
      @table "#{config.table}"

      @impl true
      def list_personal_filter_sets(user_id, domain) do
        query = \"\"\"
        SELECT * FROM \#{@table}
        WHERE user_id = $1 AND domain = $2 AND is_system = false
        ORDER BY is_default DESC, name ASC
        \"\"\"
        query_rows(query, [user_id, domain])
      end

      @impl true
      def list_shared_filter_sets(_user_id, domain) do
        query = \"\"\"
        SELECT * FROM \#{@table}
        WHERE is_shared = true AND domain = $1 AND is_system = false
        ORDER BY name ASC
        \"\"\"
        query_rows(query, [domain])
      end

      @impl true
      def list_system_filter_sets(domain) do
        query = \"\"\"
        SELECT * FROM \#{@table}
        WHERE is_system = true AND domain = $1
        ORDER BY name ASC
        \"\"\"
        query_rows(query, [domain])
      end

      @impl true
      def get_filter_set(id, user_id) do
        query = "SELECT * FROM \#{@table} WHERE id = $1::uuid"
        case query_rows(query, [id]) do
          [] -> {:error, :not_found}
          [%{"is_system" => true} = fs] -> {:ok, fs}
          [%{"is_shared" => true} = fs] -> {:ok, fs}
          [%{"user_id" => ^user_id} = fs] -> {:ok, fs}
          _ -> {:error, :unauthorized}
        end
      end

      @impl true
      def create_filter_set(attrs) do
        maybe_unset_defaults(attrs)

        query = \"\"\"
        INSERT INTO \#{@table} (name, description, domain, filters, user_id, is_default, is_shared, is_system)
        VALUES ($1, $2, $3, $4::jsonb, $5, $6, $7, $8)
        RETURNING *
        \"\"\"

        params = [
          attrs[:name] || attrs["name"],
          attrs[:description] || attrs["description"],
          attrs[:domain] || attrs["domain"],
          Jason.encode!(attrs[:filters] || attrs["filters"] || %{}),
          attrs[:user_id] || attrs["user_id"],
          attrs[:is_default] || attrs["is_default"] || false,
          attrs[:is_shared] || attrs["is_shared"] || false,
          attrs[:is_system] || attrs["is_system"] || false
        ]

        case Postgrex.query(@conn, query, params) do
          {:ok, %{rows: [row], columns: cols}} -> {:ok, row_to_map(cols, row)}
          {:error, error} -> {:error, error}
        end
      end

      @impl true
      def update_filter_set(id, attrs, user_id) do
        with {:ok, fs} <- get_filter_set(id, user_id),
             false <- fs["is_system"] do
          maybe_unset_defaults(Map.merge(fs, atomize_keys(attrs)))

          query = \"\"\"
          UPDATE \#{@table}
          SET name = COALESCE($2, name),
              description = COALESCE($3, description),
              filters = COALESCE($4::jsonb, filters),
              is_default = COALESCE($5, is_default),
              is_shared = COALESCE($6, is_shared),
              updated_at = NOW()
          WHERE id = $1::uuid
          RETURNING *
          \"\"\"

          filters_json = if f = attrs[:filters] || attrs["filters"], do: Jason.encode!(f), else: nil

          params = [
            id,
            attrs[:name] || attrs["name"],
            attrs[:description] || attrs["description"],
            filters_json,
            attrs[:is_default] || attrs["is_default"],
            attrs[:is_shared] || attrs["is_shared"]
          ]

          case Postgrex.query(@conn, query, params) do
            {:ok, %{rows: [row], columns: cols}} -> {:ok, row_to_map(cols, row)}
            {:error, error} -> {:error, error}
          end
        else
          true -> {:error, :cannot_modify_system}
          error -> error
        end
      end

      @impl true
      def delete_filter_set(id, user_id) do
        with {:ok, fs} <- get_filter_set(id, user_id),
             false <- fs["is_system"],
             true <- fs["user_id"] == user_id do
          query = "DELETE FROM \#{@table} WHERE id = $1::uuid"
          case Postgrex.query(@conn, query, [id]) do
            {:ok, _} -> {:ok, fs}
            {:error, error} -> {:error, error}
          end
        else
          true -> {:error, :cannot_delete_system}
          false -> {:error, :unauthorized}
          error -> error
        end
      end

      @impl true
      def set_default_filter_set(id, user_id) do
        with {:ok, fs} <- get_filter_set(id, user_id) do
          Postgrex.query(@conn,
            "UPDATE \#{@table} SET is_default = false WHERE user_id = $1 AND domain = $2 AND is_default = true",
            [user_id, fs["domain"]]
          )

          query = "UPDATE \#{@table} SET is_default = true, updated_at = NOW() WHERE id = $1::uuid RETURNING *"
          case Postgrex.query(@conn, query, [id]) do
            {:ok, %{rows: [row], columns: cols}} -> {:ok, row_to_map(cols, row)}
            {:error, error} -> {:error, error}
          end
        end
      end

      @impl true
      def get_default_filter_set(user_id, domain) do
        query = "SELECT * FROM \#{@table} WHERE user_id = $1 AND domain = $2 AND is_default = true"
        case query_rows(query, [user_id, domain]) do
          [fs] -> fs
          _ -> nil
        end
      end

      @impl true
      def increment_usage_count(id) do
        Postgrex.query(@conn,
          "UPDATE \#{@table} SET usage_count = usage_count + 1 WHERE id = $1::uuid",
          [id]
        )
        :ok
      end

      @impl true
      def duplicate_filter_set(id, new_name, user_id) do
        with {:ok, source} <- get_filter_set(id, user_id) do
          create_filter_set(%{
            name: new_name,
            description: source["description"],
            domain: source["domain"],
            filters: source["filters"],
            user_id: user_id,
            is_default: false,
            is_shared: false,
            is_system: false
          })
        end
      end

      # Private helpers

      defp query_rows(query, params) do
        case Postgrex.query(@conn, query, params) do
          {:ok, %{rows: rows, columns: cols}} ->
            Enum.map(rows, &row_to_map(cols, &1))
          {:error, _} -> []
        end
      end

      defp row_to_map(columns, row) do
        columns |> Enum.zip(row) |> Enum.into(%{})
      end

      defp atomize_keys(map) when is_map(map) do
        Enum.into(map, %{}, fn
          {k, v} when is_binary(k) -> {String.to_atom(k), v}
          {k, v} -> {k, v}
        end)
      end

      defp maybe_unset_defaults(attrs) do
        is_default = attrs[:is_default] || attrs["is_default"] || false
        if is_default do
          user_id = attrs[:user_id] || attrs["user_id"]
          domain = attrs[:domain] || attrs["domain"]
          if user_id && domain do
            Postgrex.query(@conn,
              "UPDATE \#{@table} SET is_default = false WHERE user_id = $1 AND domain = $2 AND is_default = true",
              [user_id, domain]
            )
          end
        end
      end
    end
    """

    create_file(context_path, content)
  end

  defp generate_tests(config) do
    test_path = "test/#{config.app_name}/filter_sets_test.exs"
    create_directory(Path.dirname(test_path))

    content = """
    defmodule #{config.context_module}Test do
      use ExUnit.Case, async: true

      # Tests require a running Postgrex connection
      # Configure in test_helper.exs

      describe "filter sets" do
        @tag :integration
        test "create_filter_set/1 creates a filter set" do
          attrs = %{
            name: "Test Filter",
            domain: "test_domain",
            filters: %{"field" => "value"},
            user_id: "user123"
          }

          assert {:ok, %{"name" => "Test Filter"}} = #{config.context_module}.create_filter_set(attrs)
        end
      end
    end
    """

    create_file(test_path, content)
  end

  defp print_instructions(config) do
    migration_step =
      if config.migration do
        "1. Run the SQL:\n   mix selecto_postgrex.setup\n   (or manually: psql -f priv/sql/create_#{config.table}.sql)"
      else
        "1. SQL generation was skipped (--no-migration). Ensure your filter_sets table exists."
      end

    Mix.shell().info("""

    Filter sets implementation generated successfully!

    Next steps:

    #{migration_step}

    2. Configure the adapter in your LiveView:

       def mount(_params, _session, socket) do
         socket = assign(socket, :filter_sets_adapter, #{config.context_module})
         {:ok, socket}
        end
    """)
  end

  defp maybe_warn_compatibility_options(config) do
    if config.schema_module do
      Mix.shell().info(
        "Note: --schema-module is accepted for compatibility but ignored in Postgrex mode"
      )
    end

    if config.repo do
      Mix.shell().info("Note: --repo is accepted for compatibility but ignored in Postgrex mode")
    end
  end
end
