defmodule Mix.Tasks.SelectoPostgrex.Gen.SavedViewConfigs do
  @shortdoc "Generate SavedViewConfigs implementation using Postgrex (no Ecto)"
  @moduledoc """
  Generate SavedViewConfigs implementation for separate view type configurations
  using raw SQL and Postgrex contexts (no Ecto required).

  ## Examples

      mix selecto_postgrex.gen.saved_view_configs MyApp

      mix selecto_postgrex.gen.saved_view_configs MyApp --table-name view_configurations

      mix selecto_postgrex.gen.saved_view_configs MyApp --dry-run

  ## Options

    * `--context-module` - Context module name (default: APP.SavedViewConfigContext)
    * `--schema-module` - Compatibility option (not used in Postgrex mode)
    * `--table-name` - Database table name (default: saved_view_configs)
    * `--repo-module` - Compatibility option (not used in Postgrex mode)
    * `--connection-name` - Named Postgrex connection (default: APP.Database)
    * `--dry-run` - Show what would be generated without creating files

  ## Generated Files

  - `priv/sql/create_saved_view_configs.sql` - SQL to create the table
  - `lib/APP/saved_view_config_context.ex` - Context using Postgrex.query
  """

  use Igniter.Mix.Task

  @impl Igniter.Mix.Task
  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      group: :selecto,
      example: "mix selecto_postgrex.gen.saved_view_configs MyApp",
      positional: [:app_name],
      schema: [
        context_module: :string,
        schema_module: :string,
        table_name: :string,
        repo_module: :string,
        connection_name: :string,
        dry_run: :boolean
      ],
      aliases: [
        c: :context_module,
        s: :schema_module,
        t: :table_name,
        r: :repo_module,
        d: :dry_run
      ]
    }
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    parsed_args = igniter.args.options
    positional = igniter.args.positional
    app_name_arg = Map.get(positional, :app_name)

    if is_nil(app_name_arg) or app_name_arg == "" do
      Igniter.add_warning(igniter, """
      App name is required. Usage:
        mix selecto_postgrex.gen.saved_view_configs MyApp
      """)
    else
      generate(igniter, app_name_arg, parsed_args)
    end
  end

  defp generate(igniter, app_name, opts) do
    config = build_config(app_name, opts)
    igniter = maybe_add_compatibility_notices(igniter, opts)

    if opts[:dry_run] do
      show_dry_run(config)
      igniter
    else
      igniter
      |> generate_sql_file(config)
      |> generate_context_file(config)
      |> add_success_messages(config)
    end
  end

  defp build_config(app_name, opts) do
    %{
      app_name: app_name,
      app_underscore: Macro.underscore(app_name),
      context_module: opts[:context_module] || "#{app_name}.SavedViewConfigContext",
      schema_module: opts[:schema_module],
      table_name: opts[:table_name] || "saved_view_configs",
      repo_module: opts[:repo_module],
      connection_name: opts[:connection_name] || "#{app_name}.Database"
    }
  end

  defp maybe_add_compatibility_notices(igniter, opts) do
    igniter
    |> maybe_add_notice(
      opts[:schema_module],
      "--schema-module is accepted for compatibility but ignored in Postgrex mode"
    )
    |> maybe_add_notice(
      opts[:repo_module],
      "--repo-module is accepted for compatibility but ignored in Postgrex mode"
    )
  end

  defp maybe_add_notice(igniter, nil, _message), do: igniter
  defp maybe_add_notice(igniter, _value, message), do: Igniter.add_notice(igniter, message)

  defp show_dry_run(config) do
    IO.puts("""

    SelectoPostgrex SavedViewConfigs Generation (DRY RUN)
    =====================================================

    Files to be generated:
      * priv/sql/create_#{config.table_name}.sql
      * lib/#{config.app_underscore}/saved_view_config_context.ex

    Modules:
      * #{config.context_module}

    Run without --dry-run to generate files.
    """)
  end

  defp generate_sql_file(igniter, config) do
    file_path = "priv/sql/create_#{config.table_name}.sql"

    content = """
    -- SavedViewConfigs table for SelectoComponents
    -- Generated by mix selecto_postgrex.gen.saved_view_configs
    -- Run with: mix selecto_postgrex.setup

    CREATE TABLE IF NOT EXISTS #{config.table_name} (
      id BIGSERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      context VARCHAR(255) NOT NULL,
      view_type VARCHAR(50) NOT NULL,  -- 'detail', 'aggregate', 'graph'
      params JSONB NOT NULL DEFAULT '{}',
      user_id VARCHAR(255),
      description TEXT,
      is_public BOOLEAN NOT NULL DEFAULT false,
      version INTEGER NOT NULL DEFAULT 1,
      inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table_name}_unique_name_per_view_type
      ON #{config.table_name} (name, context, view_type, user_id);

    CREATE INDEX IF NOT EXISTS idx_#{config.table_name}_view_type_context
      ON #{config.table_name} (view_type, context);

    CREATE INDEX IF NOT EXISTS idx_#{config.table_name}_user_id
      ON #{config.table_name} (user_id);

    CREATE INDEX IF NOT EXISTS idx_#{config.table_name}_is_public
      ON #{config.table_name} (is_public);
    """

    Igniter.create_new_file(igniter, file_path, content)
  end

  defp generate_context_file(igniter, config) do
    file_path = "lib/#{config.app_underscore}/saved_view_config_context.ex"

    content = """
    defmodule #{config.context_module} do
      @moduledoc \"\"\"
      Context module for saved view configurations with view type separation.

      Uses Postgrex.query directly (no Ecto).

      Generated by mix selecto_postgrex.gen.saved_view_configs

      ## Usage

          defmodule MyApp.Domains.UserDomain do
            use #{config.context_module}

            # ... rest of domain configuration
          end
      \"\"\"

      defmacro __using__(_opts \\\\ []) do
        conn_name = #{config.connection_name}
        table = #{inspect(config.table_name)}

        quote bind_quoted: [conn_name: conn_name, table: table] do
          @view_config_conn conn_name
          @view_config_table table

          @doc \"\"\"
          Get a saved view configuration by name, context, and view type.
          \"\"\"
          def get_view_config(name, context, view_type, opts \\\\ []) do
            user_id = Keyword.get(opts, :user_id)

            {query, params} =
              if user_id do
                {\"\"\"
                SELECT * FROM \#{@view_config_table}
                WHERE name = $1 AND context = $2 AND view_type = $3
                  AND (user_id = $4 OR is_public = true)
                LIMIT 1
                \"\"\",
                [name, context, view_type, user_id]}
              else
                {\"\"\"
                SELECT * FROM \#{@view_config_table}
                WHERE name = $1 AND context = $2 AND view_type = $3
                  AND is_public = true
                LIMIT 1
                \"\"\",
                [name, context, view_type]}
              end

            case Postgrex.query(@view_config_conn, query, params) do
              {:ok, %{rows: [row], columns: cols}} -> row_to_view_config_map(cols, row)
              {:ok, %{rows: []}} -> nil
              {:error, _} -> nil
            end
          end

          @doc \"\"\"
          Save or update a view configuration (upsert).
          \"\"\"
          def save_view_config(name, context, view_type, params, opts \\\\ []) do
            user_id = Keyword.get(opts, :user_id)
            description = Keyword.get(opts, :description)
            is_public = Keyword.get(opts, :is_public, false)
            json_params = Jason.encode!(params)

            upsert = \"\"\"
            INSERT INTO \#{@view_config_table}
              (name, context, view_type, params, user_id, description, is_public, inserted_at, updated_at)
            VALUES ($1, $2, $3, $4::jsonb, $5, $6, $7, NOW(), NOW())
            ON CONFLICT (name, context, view_type, user_id)
            DO UPDATE SET params = $4::jsonb, description = $6, is_public = $7,
                          version = \#{@view_config_table}.version + 1, updated_at = NOW()
            RETURNING *
            \"\"\"

            case Postgrex.query(@view_config_conn, upsert,
              [name, context, view_type, json_params, user_id, description, is_public]) do
              {:ok, %{rows: [row], columns: cols}} -> {:ok, row_to_view_config_map(cols, row)}
              {:error, error} -> {:error, error}
            end
          end

          @doc \"\"\"
          List view configurations for a context and view type.
          \"\"\"
          def list_view_configs(context, view_type, opts \\\\ []) do
            user_id = Keyword.get(opts, :user_id)
            include_public = Keyword.get(opts, :include_public, true)

            {query, params} =
              cond do
                user_id && include_public ->
                  {\"\"\"
                  SELECT * FROM \#{@view_config_table}
                  WHERE context = $1 AND view_type = $2
                    AND (user_id = $3 OR is_public = true)
                  ORDER BY updated_at DESC
                  \"\"\",
                  [context, view_type, user_id]}

                user_id ->
                  {\"\"\"
                  SELECT * FROM \#{@view_config_table}
                  WHERE context = $1 AND view_type = $2 AND user_id = $3
                  ORDER BY updated_at DESC
                  \"\"\",
                  [context, view_type, user_id]}

                include_public ->
                  {\"\"\"
                  SELECT * FROM \#{@view_config_table}
                  WHERE context = $1 AND view_type = $2 AND is_public = true
                  ORDER BY updated_at DESC
                  \"\"\",
                  [context, view_type]}

                true ->
                  {"SELECT * FROM \#{@view_config_table} WHERE false", []}
              end

            case Postgrex.query(@view_config_conn, query, params) do
              {:ok, %{rows: rows, columns: cols}} ->
                Enum.map(rows, &row_to_view_config_map(cols, &1))
              {:error, _} -> []
            end
          end

          @doc \"\"\"
          Delete a view configuration.
          \"\"\"
          def delete_view_config(name, context, view_type, opts \\\\ []) do
            user_id = Keyword.get(opts, :user_id)

            case get_view_config(name, context, view_type, user_id: user_id) do
              nil ->
                {:error, :not_found}

              %{"user_id" => ^user_id} = config_map ->
                query = "DELETE FROM \#{@view_config_table} WHERE id = $1"
                case Postgrex.query(@view_config_conn, query, [config_map["id"]]) do
                  {:ok, _} -> {:ok, config_map}
                  {:error, error} -> {:error, error}
                end

              _ ->
                {:error, :unauthorized}
            end
          end

          @doc \"\"\"
          Update a view configuration.
          \"\"\"
          def update_view_config(name, context, view_type, params, opts \\\\ []) do
            user_id = Keyword.get(opts, :user_id)
            description = Keyword.get(opts, :description)
            is_public = Keyword.get(opts, :is_public)

            case get_view_config(name, context, view_type, user_id: user_id) do
              nil ->
                {:error, :not_found}

              %{"user_id" => ^user_id} = config_map ->
                json_params = Jason.encode!(params)

                query = \"\"\"
                UPDATE \#{@view_config_table}
                SET params = $2::jsonb,
                    description = COALESCE($3, description),
                    is_public = COALESCE($4, is_public),
                    version = version + 1,
                    updated_at = NOW()
                WHERE id = $1
                RETURNING *
                \"\"\"

                case Postgrex.query(@view_config_conn, query,
                  [config_map["id"], json_params, description, is_public]) do
                  {:ok, %{rows: [row], columns: cols}} -> {:ok, row_to_view_config_map(cols, row)}
                  {:error, error} -> {:error, error}
                end

              _ ->
                {:error, :unauthorized}
            end
          end

          @doc \"\"\"
          Get just the names of saved view configs for a context and view type.
          \"\"\"
          def get_view_config_names(context, view_type, opts \\\\ []) do
            configs = list_view_configs(context, view_type, opts)
            Enum.map(configs, fn c -> c["name"] end)
          end

          @doc \"\"\"
          Decode a view configuration to get its params.
          \"\"\"
          def decode_view_config(view_config) when is_map(view_config) do
            view_config["params"] || view_config[:params]
          end

          defp row_to_view_config_map(columns, row) do
            columns
            |> Enum.zip(row)
            |> Enum.into(%{})
          end
        end
      end
    end
    """

    Igniter.create_new_file(igniter, file_path, content)
  end

  defp add_success_messages(igniter, config) do
    igniter
    |> Igniter.add_notice("Generated SQL: priv/sql/create_#{config.table_name}.sql")
    |> Igniter.add_notice("Generated context: #{config.context_module}")
    |> Igniter.add_notice("""

    Next steps:
    1. Run: mix selecto_postgrex.setup  (or execute the SQL manually)
    2. Add 'use #{config.context_module}' to your domain modules
    3. Update your LiveView to use view_type when saving/loading configs
    """)
  end
end
