defmodule Mix.Tasks.SelectoPostgrex.Gen.SavedViews do
  @shortdoc "Generate SavedViews implementation using Postgrex (no Ecto)"
  @moduledoc """
  Generate SavedViews implementation for SelectoComponents using raw SQL
  and Postgrex contexts (no Ecto required).

  ## Examples

      mix selecto_postgrex.gen.saved_views MyApp

      mix selecto_postgrex.gen.saved_views MyApp --table-name custom_saved_views

      mix selecto_postgrex.gen.saved_views MyApp --dry-run

  ## Options

    * `--context-module` - Context module name (default: APP.SavedViewContext)
    * `--table-name` - Database table name (default: saved_views)
    * `--connection-name` - Named Postgrex connection (default: APP.Database)
    * `--dry-run` - Show what would be generated without creating files

  ## Generated Files

  - `priv/sql/create_saved_views.sql` - SQL to create the table
  - `lib/APP/saved_view_context.ex` - Context using Postgrex.query
  """

  use Igniter.Mix.Task

  @impl Igniter.Mix.Task
  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      group: :selecto,
      example: "mix selecto_postgrex.gen.saved_views MyApp",
      positional: [:app_name],
      schema: [
        context_module: :string,
        table_name: :string,
        connection_name: :string,
        dry_run: :boolean
      ],
      aliases: [
        c: :context_module,
        t: :table_name,
        d: :dry_run
      ]
    }
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    parsed_args = igniter.args.options
    positional = igniter.args.positional
    app_name_arg = Map.get(positional, :app_name)

    if is_nil(app_name_arg) or app_name_arg == "" do
      Igniter.add_warning(igniter, """
      App name is required. Usage:
        mix selecto_postgrex.gen.saved_views MyApp
      """)
    else
      generate(igniter, app_name_arg, parsed_args)
    end
  end

  defp generate(igniter, app_name, opts) do
    config = build_config(app_name, opts)

    if opts[:dry_run] do
      show_dry_run(config)
      igniter
    else
      igniter
      |> generate_sql_file(config)
      |> generate_context_file(config)
      |> add_success_messages(config)
    end
  end

  defp build_config(app_name, opts) do
    %{
      app_name: app_name,
      app_underscore: Macro.underscore(app_name),
      context_module: opts[:context_module] || "#{app_name}.SavedViewContext",
      table_name: opts[:table_name] || "saved_views",
      connection_name: opts[:connection_name] || "#{app_name}.Database"
    }
  end

  defp show_dry_run(config) do
    IO.puts("""

    SelectoPostgrex SavedViews Generation (DRY RUN)
    ================================================

    Files to be generated:
      * priv/sql/create_#{config.table_name}.sql
      * lib/#{config.app_underscore}/saved_view_context.ex

    Modules:
      * #{config.context_module}

    Run without --dry-run to generate files.
    """)
  end

  defp generate_sql_file(igniter, config) do
    file_path = "priv/sql/create_#{config.table_name}.sql"

    content = """
    -- SavedViews table for SelectoComponents
    -- Generated by mix selecto_postgrex.gen.saved_views
    -- Run with: mix selecto_postgrex.setup

    CREATE TABLE IF NOT EXISTS #{config.table_name} (
      id BIGSERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      context VARCHAR(255) NOT NULL,
      params JSONB NOT NULL DEFAULT '{}',
      inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table_name}_name_context
      ON #{config.table_name} (name, context);
    """

    Igniter.create_new_file(igniter, file_path, content)
  end

  defp generate_context_file(igniter, config) do
    file_path = "lib/#{config.app_underscore}/saved_view_context.ex"

    content = """
    defmodule #{config.context_module} do
      @moduledoc \"\"\"
      Context module implementing SelectoComponents.SavedViews behaviour.

      Uses Postgrex.query directly (no Ecto).

      Generated by mix selecto_postgrex.gen.saved_views

      ## Usage

          defmodule MyApp.Domains.UserDomain do
            use #{config.context_module}

            # ... rest of domain configuration
          end
      \"\"\"

      defmacro __using__(_opts \\\\ []) do
        conn_name = #{config.connection_name}
        table = #{inspect(config.table_name)}

        quote bind_quoted: [conn_name: conn_name, table: table] do
          @behaviour SelectoComponents.SavedViews

          @saved_views_conn conn_name
          @saved_views_table table

          def get_view(name, context) do
            query = "SELECT id, name, context, params, inserted_at, updated_at FROM \#{@saved_views_table} WHERE context = $1 AND name = $2"

            case Postgrex.query(@saved_views_conn, query, [context, name]) do
              {:ok, %{rows: [row], columns: cols}} ->
                row_to_map(cols, row)

              {:ok, %{rows: []}} ->
                nil

              {:error, _} ->
                nil
            end
          end

          def save_view(name, context, params) do
            json_params = Jason.encode!(params)

            upsert = \"\"\"
            INSERT INTO \#{@saved_views_table} (name, context, params, inserted_at, updated_at)
            VALUES ($1, $2, $3::jsonb, NOW(), NOW())
            ON CONFLICT (name, context) DO UPDATE SET params = $3::jsonb, updated_at = NOW()
            RETURNING id, name, context, params, inserted_at, updated_at
            \"\"\"

            case Postgrex.query(@saved_views_conn, upsert, [name, context, json_params]) do
              {:ok, %{rows: [row], columns: cols}} -> row_to_map(cols, row)
              {:error, error} -> {:error, error}
            end
          end

          def get_view_names(context) do
            query = "SELECT name FROM \#{@saved_views_table} WHERE context = $1 ORDER BY name"

            case Postgrex.query(@saved_views_conn, query, [context]) do
              {:ok, %{rows: rows}} -> Enum.map(rows, fn [name] -> name end)
              {:error, _} -> []
            end
          end

          def decode_view(view) when is_map(view) do
            view["params"] || view[:params]
          end

          defp row_to_map(columns, row) do
            columns
            |> Enum.zip(row)
            |> Enum.into(%{})
          end
        end
      end
    end
    """

    Igniter.create_new_file(igniter, file_path, content)
  end

  defp add_success_messages(igniter, config) do
    igniter
    |> Igniter.add_notice("Generated SQL: priv/sql/create_#{config.table_name}.sql")
    |> Igniter.add_notice("Generated context: #{config.context_module}")
    |> Igniter.add_notice("""

    Next steps:
    1. Run: mix selecto_postgrex.setup  (or execute the SQL manually)
    2. Add 'use #{config.context_module}' to your domain modules
    3. Set saved_view_context assign in your LiveViews
    """)
  end
end
